In [1]:
!wget https://raw.githubusercontent.com/ashwinvaswani/whatif/master/Data/match_info_final_updated_normalized.csv?token=AFQLSH4HULON2XF56IL2HYS63U6PO

--2020-06-01 08:26:20--  https://raw.githubusercontent.com/ashwinvaswani/whatif/master/Data/match_info_final_updated_normalized.csv?token=AFQLSH4HULON2XF56IL2HYS63U6PO
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 143493 (140K) [text/plain]
Saving to: ‘match_info_final_updated_normalized.csv?token=AFQLSH4HULON2XF56IL2HYS63U6PO’

match_info_final_up 100%[===================>] 140.13K  --.-KB/s    in 0.04s

2020-06-01 08:26:20 (3.39 MB/s) - ‘match_info_final_updated_normalized.csv?token=AFQLSH4HULON2XF56IL2HYS63U6PO’ saved [143493/143493]

In [0]:
import pandas as pd
df = pd.read_csv("match_info_final_updated_normalized.csv?token=AFQLSH4HULON2XF56IL2HYS63U6PO")

In [4]:
df.head()

   Unnamed: 0  ...  Wembley Stadium, London
0           0  ...                      0.0
1           1  ...                      0.0
2           2  ...                      0.0
3           3  ...                      0.0
4           4  ...                      0.0

[5 rows x 61 columns]

In [0]:
full_list = []
for index, row in df.iterrows():
    embed_whole = []
    embed_whole.append(row.Goals)
    embed_whole.append(row["On Target"])
    embed_whole.append(row["Off Target"])
    embed_whole.append(row["Blocks"])
    embed_whole.append(row["Corners"])
    embed_whole.append(row["Offside"])
    embed_whole.append(row["Possession"])
    embed_whole.append(row["Passes"])
    embed_whole.append(row["Passing Accuracy"])
    embed_whole.append(row["Distance Covered"])
    embed_whole.append(row["Tackles"])
    embed_whole.append(row["Clearances"])
    embed_whole.append(row["Fouls"])
    embed_whole.append(row["Yellow Cards"] + row["Red Cards"])
    full_list.append(embed_whole)

In [0]:
df["Full Embeddings"] = full_list

In [0]:
team_dict = {}
for i,row in df.iterrows():
    if row["Teams"] not in team_dict:
        team_dict[row["Teams"]] = []
        team_dict[row["Teams"]].append(row["Full Embeddings"])
    else:
        team_dict[row["Teams"]].append(row["Full Embeddings"])

In [0]:
import numpy as np
team_name = []
team_embed = []
for i in team_dict:
    temp = np.mean(np.array(team_dict[i]), axis=0)
    team_name.append(i)
    team_embed.append(temp)

In [0]:
fd = pd.DataFrame()
fd["Teams"] = team_name
fd["Embeddings"] = team_embed

In [0]:
fd.to_csv("Team_embeddings.csv",index=False)

In [19]:
!wget https://raw.githubusercontent.com/ashwinvaswani/whatif/master/Data/player_info_final_updated_normalized.csv?token=AFQLSH23VWLDJSPKDZGGLTS63X44Q

--2020-06-01 08:41:53--  https://raw.githubusercontent.com/ashwinvaswani/whatif/master/Data/player_info_final_updated_normalized.csv?token=AFQLSH23VWLDJSPKDZGGLTS63X44Q
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 464610 (454K) [text/plain]
Saving to: ‘player_info_final_updated_normalized.csv?token=AFQLSH23VWLDJSPKDZGGLTS63X44Q’

player_info_final_u 100%[===================>] 453.72K  --.-KB/s    in 0.08s

2020-06-01 08:41:53 (5.89 MB/s) - ‘player_info_final_updated_normalized.csv?token=AFQLSH23VWLDJSPKDZGGLTS63X44Q’ saved [464610/464610]

In [0]:
df = pd.read_csv("player_info_final_updated_normalized.csv?token=AFQLSH23VWLDJSPKDZGGLTS63X44Q")

In [21]:
df.head()

   Unnamed: 0  Unnamed: 0.1  ... Offsides Time Played
0           0             0  ...      0.0    1.000000
1           1             1  ...      0.0    1.000000
2           2             2  ...      0.0    1.000000
3           3             3  ...      0.0    0.944444
4           4             4  ...      0.0    1.000000

[5 rows x 13 columns]

In [0]:
full_list = []
for index, row in df.iterrows():
    embed_whole = []
    embed_whole.append(row["Time Played"])
    embed_whole.append(row["Total shots"])
    embed_whole.append(row["Shots on Target"])
    embed_whole.append(row["Goals scored"])
    embed_whole.append(row["Assists"])
    embed_whole.append(row["Crosses"])
    embed_whole.append(row["Interceptions"])
    embed_whole.append(row["Fouls committed"])
    embed_whole.append(row["Offsides"])
    full_list.append(embed_whole)

In [0]:
df["Full Embeddings"] = full_list

In [0]:
player_dict = {}
for i,row in df.iterrows():
    if row["Players"] not in player_dict:
        player_dict[row["Players"]] = []
        player_dict[row["Players"]].append(row["Full Embeddings"])
    else:
        player_dict[row["Players"]].append(row["Full Embeddings"])

In [0]:
import numpy as np
player_name = []
player_embed = []
for i in player_dict:
    temp = np.mean(np.array(player_dict[i]), axis=0)
    player_name.append(i)
    player_embed.append(temp)

In [0]:
fd = pd.DataFrame()
fd["Players"] = player_name
fd["Embeddings"] = player_embed

In [0]:
fd.to_csv("Player_embeddings.csv",index=False)