In [1]:
import pandas as pd
import numpy as np

In [3]:
matches_df = pd.read_csv('./../Data/matches_info.csv')
players_df = pd.read_csv('./../Data/players_info.csv')

In [4]:
matches_df.head()

,Teams,Stadium,Goals,Total Attempts,On Target,Off Target,Blocked,Woodwork,Corners,Offside,...,Passing Accuracy,Passes Completed,Distance Covered,Balls Recovered,Tackles,Clearances,Blocks,Yellow Cards,Red Cards,Fouls
0,Juventus,"Olympiastadion, Berlin",1,Not Provided,6,6,2,Not Provided,8,1,...,Not Provided,286,114.3 km,28,4,11,0,2,0,24
1,Barcelona,"Olympiastadion, Berlin",3,Not Provided,8,6,0,Not Provided,8,0,...,Not Provided,505,112.0 km,39,2,15,2,1,0,12
2,Real Madrid,"Estadio Santiago Bernabéu, Madrid",1,Not Provided,5,14,3,Not Provided,8,0,...,Not Provided,459,108.8 km,49,5,14,1,2,0,11
3,Juventus,"Estadio Santiago Bernabéu, Madrid",1,Not Provided,4,14,1,Not Provided,8,5,...,Not Provided,368,116.3 km,44,3,27,3,2,0,7
4,Bayern,"Football Arena Munich, Munich",3,Not Provided,8,8,4,Not Provided,5,3,...,Not Provided,526,114.7 km,55,3,5,1,5,0,19

In [6]:
matches_df['Total Attempts'] = matches_df['On Target'] + matches_df['Off Target']

In [7]:
matches_df['Passing Accuracy'] = matches_df['Passes Completed'] / matches_df['Passes']

In [8]:
matches_df.head()

,Teams,Stadium,Goals,Total Attempts,On Target,Off Target,Blocked,Woodwork,Corners,Offside,...,Passing Accuracy,Passes Completed,Distance Covered,Balls Recovered,Tackles,Clearances,Blocks,Yellow Cards,Red Cards,Fouls
0,Juventus,"Olympiastadion, Berlin",1,12,6,6,2,Not Provided,8,1,...,0.833819,286,114.3 km,28,4,11,0,2,0,24
1,Barcelona,"Olympiastadion, Berlin",3,14,8,6,0,Not Provided,8,0,...,0.885965,505,112.0 km,39,2,15,2,1,0,12
2,Real Madrid,"Estadio Santiago Bernabéu, Madrid",1,19,5,14,3,Not Provided,8,0,...,0.907115,459,108.8 km,49,5,14,1,2,0,11
3,Juventus,"Estadio Santiago Bernabéu, Madrid",1,18,4,14,1,Not Provided,8,5,...,0.851852,368,116.3 km,44,3,27,3,2,0,7
4,Bayern,"Football Arena Munich, Munich",3,16,8,8,4,Not Provided,5,3,...,0.878130,526,114.7 km,55,3,5,1,5,0,19

In [27]:
matches_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 290 entries, 0 to 289
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Teams             290 non-null    category
 1   Stadium           290 non-null    object
 2   Goals             290 non-null    int64
 3   Total Attempts    290 non-null    int64
 4   On Target         290 non-null    int64
 5   Off Target        290 non-null    int64
 6   Blocked           290 non-null    int64
 7   Woodwork          174 non-null    object
 8   Corners           290 non-null    int64
 9   Offside           290 non-null    int64
 10  Possession        290 non-null    object
 11  Passes            290 non-null    int64
 12  Passing Accuracy  290 non-null    float64
 13  Passes Completed  290 non-null    int64
 14  Distance Covered  290 non-null    object
 15  Balls Recovered   290 non-null    int64
 16  Tackles           290 non-null    int64
 17  Clearances        290 non-null    int64
 18  Blocks            290 non-null    int64
 19  Yellow Cards      290 non-null    int64
 20  Red Cards         290 non-null    int64
 21  Fouls             290 non-null    int64
 22  Temp              290 non-null    int64
dtypes: category(1), float64(1), int64(17), object(4)
memory usage: 51.8+ KB

In [18]:
matches_df[matches_df['Possession'] != 'Not Provided'].shape

(290, 22)

In [15]:
matches_df = matches_df.replace(r'Not Provided', np.nan, regex=True)

In [24]:
matches_df['Teams'] = matches_df["Teams"].astype('category')

In [28]:
from sklearn.preprocessing import LabelEncoder
lb = LabelEncoder()
matches_df['Temp'] = lb.fit_transform(matches_df['Teams'])
matches_df.head()

,Teams,Stadium,Goals,Total Attempts,On Target,Off Target,Blocked,Woodwork,Corners,Offside,...,Passes Completed,Distance Covered,Balls Recovered,Tackles,Clearances,Blocks,Yellow Cards,Red Cards,Fouls,Temp
0,Juventus,"Olympiastadion, Berlin",1,12,6,6,2,NaN,8,1,...,286,114.3 km,28,4,11,0,2,0,24,12
1,Barcelona,"Olympiastadion, Berlin",3,14,8,6,0,NaN,8,0,...,505,112.0 km,39,2,15,2,1,0,12,3
2,Real Madrid,"Estadio Santiago Bernabéu, Madrid",1,19,5,14,3,NaN,8,0,...,459,108.8 km,49,5,14,1,2,0,11,24
3,Juventus,"Estadio Santiago Bernabéu, Madrid",1,18,4,14,1,NaN,8,5,...,368,116.3 km,44,3,27,3,2,0,7,12
4,Bayern,"Football Arena Munich, Munich",3,16,8,8,4,NaN,5,3,...,526,114.7 km,55,3,5,1,5,0,19,5

In [29]:
matches_df['Woodwork'] = matches_df['Woodwork'].fillna(matches_df.groupby('Temp')['Woodwork'].transform('mean'))

DataError: No numeric types to aggregate

KeyError: 'Column not found: 1'